import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "@chakra-ui/react";
import NumberRange from "@/components/NumberInput";
import { useEffect, useState } from 'react';
import PocketBase from 'pocketbase';
import { Box } from "@chakra-ui/react"
import { Text } from "@chakra-ui/react";
import ProductCard from "@/components/products";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const pb = new PocketBase("http://localhost:8090")

  const [product, setProduct] = useState(null)
  useEffect(() => {
    async function getProduct() {
      const result = await pb.collection("products").getOne('f5xocya32th86w1')
      setProduct(result);
      console.log(result)
    }

    getProduct();
  }, []);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href='/'><img src='logo.avif'></img></a>
      <main style={{
        display: "flex",
        width: "100%",
        alignproducts: "center",
      }}>
        {product ? (
          <>
            <ProductCard product={product} />
          </>
        ) : (
          <p style={{ fontWeight: 700, fontSize: "2rem" }}>Loading...</p>
        )}
        <p style={{color:'white',maxWidth:'400px',paddingTop:'4rem',paddingLeft:'2rem'}}>Golf Groovy know's the importance of a clean club as a dirty club leads to reduced ball control and spin.

Elevate Your Golf Game: Keep your clubs pristine with our golf club cleaner and improve performance with clean grooves

Efficient Cleaning with Water Spray: Our innovative golf club brush features a water spray for effortless club cleaning, ensuring better shots on the course

Magnetic Clip: Our super strong magnet allows you to easily attach it to your bag for quick access and convenience, Groovy also comes with additional plastic clip with recommended use on carry bags

 Safe & Gentle Cleaning: Our golf club cleaner is designed to protect club finishes while effectively removing dirt and debris from balls and grooves

Portable Accessory for Golf Bags: Lightweight and easily attachable, our golf club cleaner is one of the must-have golf accessories for every golfer

Perfect Golf Gift: Surprise any golf enthusiast with this practical and thoughtful golf club cleaning accessory – a great addition to their golf bag</p>
      </main>
    </>
  );
}
