import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import NumberRange from "@/components/NumberInput";
import { Box } from "@chakra-ui/react"


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Golf groovy</title>#
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <b>Golf groovy</b>
      <main style={{
        display: "flex",
        flexDirection: "row",
        width: "100%",
        alignItems: "center",
      }}>
       <NumberRange />
            <Button style={{
                color: "black"
            }} colorScheme='whatsapp'><b>
                    Add to cart
                </b>
            </Button>
      </main>
    </>
  );
}
